SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
WHERE (SELECT COUNT(*)
       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
       WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' AND A.CAR_ID = CAR_ID
       GROUP BY CAR_ID
      ) >= 5 AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH(START_DATE) ASC,CAR_ID DESC;
