WITH RECURSIVE TIME_TBL AS(
    SELECT 0 AS TIME
    UNION ALL 
    SELECT TIME + 1 FROM TIME_TBL
    WHERE TIME < 23
)

SELECT TIME AS HOUR, COUNT(DISTINCT ANIMAL_ID)
FROM ANIMAL_OUTS RIGHT JOIN TIME_TBL ON HOUR(ANIMAL_OUTS.DATETIME) = TIME_TBL.TIME
GROUP BY TIME
