SELECT USER_ID, NICKNAME,  SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD JOIN USED_GOODS_USER  ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_PRICE >= 700000
ORDER BY TOTAL_PRICE;
